### ISSUE TITLE
Bad formatting on syndesis.io

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis.io#203]
Some pages have problematic layout

https://syndesis.io/docs/contributing/engineering_guidelines/

<img width="1140" alt="Screen Shot 2020-12-09 at 4 15 52 PM" src="https://user-images.githubusercontent.com/35576/101648148-d372e000-3a39-11eb-8e38-895a5b00b140.png">

I'm seeing this on both safari as well as chrome.

**Comment by kahboom** [comment]
For me, the problem seems to be happening when resizing the window to somewhere between 50% and ~65% (two thirds) of the screen width, or 1,024 x 442. At 50% it hides the sidebar and TOC as expected.

The threshold for when the sidebar and TOC should be collapsed/hidden needs to be updated, but I can't seem to get the site to run locally anymore. I tried updating from node v10.15.3 to v14.15.1. @zregvart  would you mind taking a look, or sharing what versions of node and yarn you're using to run the site locally?

**Comment by zregvart** [comment]
@kahboom I use v12.20.0 which seems to work. I've created #205 so now with help of nvm the version of nodejs can be switched to v12. We could also lock stuff down much more and upgrade to v14 LTS with Yarn PnP and zero install, though I don't think we absolutely need to, we don't make a lot of changes to the website really.
