### ISSUE TITLE
oauth proxy with rh-sso/keycloak

### ISSUE THREAD

**Issue by david-rh** [syndesisio/syndesis.io#79]
I am trying to deploy to openshift, and the deployment runs successfully.  But when I attempt to access the service, I get a 504 timeout after logging in.  I am using RH-SSO for my openshift authentication.  And in the logs for the oauthproxy I am seeing the following error:

2018/04/04 17:58:00 oauthproxy.go:635: error redeeming code (client:10.128.0.1:34586): Post https://rhsledcloud.net:8443/oauth/token: dial tcp 13.59.116.22:8443: getsockopt: connection timed out

Any idea on what I might be missing in my setup for this to work.

**Comment by rhuss** [comment]
Hey @david-rh thanks for trying Syndesis !

It looks like a generic oauthproxy issue, Syndesis doesn't do change much here. So the community at https://github.com/openshift/oauth-proxy can help here.

Otherwise, if you have specific issues about Syndesis, please open issues at https://github.com/syndesisio/syndesis as this repo here is only about the website itself (and we don't really track issues here). 

'hope you dont mind that I close this issue and see you over there at https://github.com/syndesisio/syndesis !
